# Generated by Django 5.0.4 on 2024-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TablespaceExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, db_tablespace="indexes", max_length=30
                    ),
                ),
                ("data", models.CharField(db_index=True, max_length=255)),
                ("shortcut", models.CharField(max_length=7)),
                (
                    "edges",
                    models.ManyToManyField(
                        db_tablespace="indexes", to="learning.tablespaceexample"
                    ),
                ),
            ],
            options={
                "db_tablespace": "tables",
                "indexes": [
                    models.Index(
                        db_tablespace="other_indexes",
                        fields=["shortcut"],
                        name="learning_ta_shortcu_8c2341_idx",
                    )
                ],
            },
        ),
    ]
