# Generated by Django 5.0.4 on 2024-08-07 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_topping_pizza"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "best_pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="championed_by",
                        to="learning.pizza",
                    ),
                ),
                (
                    "pizzas",
                    models.ManyToManyField(
                        related_name="restaurants", to="learning.pizza"
                    ),
                ),
            ],
        ),
    ]
