# -*- coding: utf-8 -*-
# Generated by Django 5.0.4 on 2024-08-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="toppings",
            field=models.ManyToManyField(related_name="pizza", to="learning.topping"),
        ),
    ]
